name: default
kind: postgres
configuration:
  connection_info:
    database_url:
      from_env: HASURA_GRAPHQL_DATABASE_URL
    pool_settings:
      max_connections: 50
      idle_timeout: 180
      retries: 1
      pool_timeout: 360
      connection_lifetime: 600
    isolation_level: read-committed
    use_prepared_statements: true
customization:
  root_fields:
    namespace: coding
  type_names:
    prefix: coding_
tables: "!include tables/tables.yaml"
